### ISSUE TITLE
Album level is being ignored

### ISSUE THREAD

**Issue by daendaen** [Salvoxia/immich-folder-album-creator#16]
My folder structure is as follows:

/import
  └── mainfolder 1/ some pictures in mainfolder 1
      ├── subfolder 1/ some pictures in subfolder 
      └── subfolder 2/ some pictures in subfolder 
  └── mainfolder 2/ some pictures in mainfolder 2
      ├── subfolder 3/ some pictures in subfolder 
      └── subfolder 4/ some pictures in subfolder 

etc.

No matter which level I set, albums are always created only for the main folder.

The command I'm using to execute it is:

docker run -e ALBUM_LEVEL=2 --name immich-folder-album -e API_URL="http://XXX.XXX.XXX.XXX:8080/api/" -e API_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXX" -e ROOT_PATH="/import" salvoxia/immich-folder-album-creator:latest /script/immich_auto_album.sh

Does anyone have an idea?

My system is an Unraid server running Docker. I installed Immich through the internal App Shop. I installed the folder creator via the Unraid console.

Greetings

**Comment by Salvoxia** [comment]
Hi,

looking at the command it seems like there's a typo in the `ALBUM_LEVEL` environment variable. It should be `ALBUM_LEVELS` (please refer to the [Environment Variables Table](https://github.com/Salvoxia/immich-folder-album-creator?tab=readme-ov-file#environment-variables)).

Best Regards,
Salvoxia

**Comment by daendaen** [comment]
Embarrassing, it's basically like here  (https://github.com/Salvoxia/immich-folder-album-creator/issues/5) except I wrote LEVEL instead of LEVELS. Oh man, thank you very much. Sometimes it's just too late for these things.
