### ISSUE TITLE
Does this project support multi-user?

### ISSUE THREAD

**Issue by drmcachr** [Salvoxia/immich-folder-album-creator#21]
I mean support multi API-Key for multi-user on immich server?

**Comment by Salvoxia** [comment]
Please take a look at [this](https://github.com/Salvoxia/immich-folder-album-creator/issues/9#issuecomment-2082149340).
Is that sufficient for your use case?

**Comment by drmcachr** [comment]
oh, thanks a lot, I have 4 account for my famlily, it's a little complex but should work.

**Comment by Salvoxia** [comment]
Closing as seems to be answered.
