### ISSUE TITLE
Can not scan the folder while running the code.

### ISSUE THREAD

**Issue by hinson-li** [Salvoxia/immich-folder-album-creator#22]
Hello, i am still new to TrueNAS and i don't know is it a dumb question or not.
I try to run the code in my TrueNAS scale via SSH.
The program can get the photos number, however it can not get the albums from the file name.

time=2024-07-24T20:48:21.957-07:00 level=INFO msg=Detected Immich server version 1.109.2
time=2024-07-24T20:48:21.957-07:00 level=INFO msg=Requesting all assets
time=2024-07-24T20:48:33.998-07:00 level=INFO msg=75744 photos found
time=2024-07-24T20:48:33.998-07:00 level=INFO msg=Sorting assets to corresponding albums using folder name
time=2024-07-24T20:48:34.027-07:00 level=INFO msg=0 albums identified
time=2024-07-24T20:48:34.027-07:00 level=INFO msg=Album list: []

Would it be a problem if i name the file and dataset with spacebar? As i call the program like this
sudo python3 ./immich_auto_album.py /mnt/My\ HDD/Media/Google\ Drive\ backup [myapiurl] [myapikey]
Or i should run the code in an other way?

My TrueNAS version is :Dragonfish-24.04.2
Immich Version:1.109.2

**Comment by hinson-li** [comment]
I just find out that i don't need to type the whole path to the code instead of just the same path in immich external library.
so it will be /'Google Drive backup' instead of the /mnt/My\ HDD/Media/Google\ Drive\ backup

**Comment by Salvoxia** [comment]
That's what I tried to document in [this part of the README file](https://github.com/Salvoxia/immich-folder-album-creator?tab=readme-ov-file#the-root_path). Does this part clarify what you need to know or is there any way to improve on that documentation from your point of view?

**Comment by hinson-li** [comment]
Yes it helps. Thanks for writing this script, it is very convenience.

**Comment by Salvoxia** [comment]
Ok thanks, closing this issue then.
