### ISSUE TITLE
Add option to ignore specific folders

### ISSUE THREAD

**Issue by clombt** [Salvoxia/immich-folder-album-creator#23]
Hi,

I really like this tool. It works great and is perfect for my usecase of immich. Due to the way how my photo library is structured I wanted to add the feature to ignore certain folders. I thought this might be a nice feature for other users too and it could be added to this repo.

I just added an additional argument at the top, which takes the folder list separated by a colon:
```python3
parser.add_argument("-i", "--ignore", default="", type=str, help="A string containing a list of folders separated by ':' that will be ignored if found in the album name.")
ignore_albums = args["ignore"]
if not ignore_albums == "":
    ignore_albums = ignore_albums.split(":")
else:
    ignore_albums = False
```
After fetching all the assets and the object `album_to_assets` is created, I remove the albums that are in the ignored list:
```python3
# Ignore albums
if ignore_albums is not False:
    keys_to_remove = [key for key in album_to_assets if any(word in key for word in ignore_albums)]
    for key in keys_to_remove:
        del album_to_assets[key]
```

Thanks for creating this script!

**Comment by Salvoxia** [comment]
Thanks for that idea!
One question about your use case: Since Immich has the possibility to add exclusion paths in the external library settings, do you want to import images from your external libraries to Immich but you do __not__ to add them to any albums?

**Comment by clombt** [comment]
Yes, this is the case for me sometimes. For example, when the folder just contains a bunch of random pictures. I guess it's not very common.

**Comment by Salvoxia** [comment]
Implemented with [0.7.0](https://github.com/Salvoxia/immich-folder-album-creator/releases/tag/0.7.0).
I used your code as a template, but the actual implementation is a little bit different. Instead of removing entries from `album_to_assets`, the asset is not considered for album creation if its path contains an entry from `ignore_albums`.

Thanks again for the proposal!

**Comment by dsakura** [comment]
Hello! How I add a list of folders to be ignored?
IGNORE: "folder_1" "folder_2" ?
Thanks

**Comment by Salvoxia** [comment]
When using Docker, pass a colon `:` separated string
`IGNORE: "folder_1:folder_2"`

**Comment by salmanuc** [comment]
> When using Docker, pass a colon `:` separated string `IGNORE: "folder_1:folder_2"`

can we use this like folder_1:* to ignore all subfolders of folder_1 but create album for folder_1 or *:Videos:* so that ignores making albums for the Videos folder but does for other folders?
i am using this in docker

**Comment by Salvoxia** [comment]
`IGNORE` works with GLOB patterns, so to ignore all subfolders of `folder_1` but include assets directly in `folder_1` you could use a pattern like this:
`IGNORE: "**/folder_1/*/**"`
This assumes that you don't have multiple paths that contain `folder_1` at different levels. If so, you need to specify the fully qualified path down to `folder_1`, like this:
`IGNORE: "/mnt/external_lib/folder_1/*/**"`

See this [example](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2Ffolder_1%2F%2A%2F%2A%2A&matches=false&tests=%2Fmnt%2Fexternal_lib%2Ffolder_1%2Fcreate_an_album_for_me.png&tests=%2Fmnt%2Fexternal_lib%2Ffolder_1%2Fignore1%2Fsome_asset.png&tests=%2Fmnt%2Fexternal_lib%2Ffolder_1%2Fignore2%2Fignore_me.png): All entries highlighted in blue are ignored.
