### ISSUE TITLE
No albums identified

### ISSUE THREAD

**Issue by Warlik** [Salvoxia/immich-folder-album-creator#24]
Hello,

I have already seen several issues with this problem. Mostly it was due to the wrong root path. If I am not thinking completely wrong, then this should not be the problem for me. The 0 photos are correct because it is a fresh instance. In previous attempts with test images in it, existing images were also displayed, which were already imported into Immich.

Immich runs as a docker container in a LXC in proxmox. The OS is Debian 12.

```
warlik@docker:~/docker/immich$ python3 ./immich_auto_album.py /external_libs/photos http://192.168.188.181:2283/api XXXXXXXXXXXXX
time=2024-07-28T15:02:25.537+00:00 level=INFO msg=Detected Immich server version 1.110.0
time=2024-07-28T15:02:25.537+00:00 level=INFO msg=Requesting all assets
time=2024-07-28T15:02:25.550+00:00 level=INFO msg=0 photos found
time=2024-07-28T15:02:25.550+00:00 level=INFO msg=Sorting assets to corresponding albums using folder name
time=2024-07-28T15:02:25.550+00:00 level=INFO msg=0 albums identified
time=2024-07-28T15:02:25.550+00:00 level=INFO msg=Album list: []
Press Enter to continue, Ctrl+C to abort

time=2024-07-28T15:02:36.424+00:00 level=INFO msg=Listing existing albums on immich
time=2024-07-28T15:02:36.437+00:00 level=INFO msg=0 existing albums identified
time=2024-07-28T15:02:36.437+00:00 level=INFO msg=Creating albums if needed
time=2024-07-28T15:02:36.437+00:00 level=INFO msg=0 albums created
time=2024-07-28T15:02:36.437+00:00 level=INFO msg=Adding assets to albums
time=2024-07-28T15:02:36.437+00:00 level=INFO msg=Done!
```

The path is actually in the docker container:

```
warlik@docker:~/docker/immich$ docker exec -it cc2ca1bdd283 bash
root@cc2ca1bdd283:/usr/src/app# cd
root@cc2ca1bdd283:~# ls /external_libs/photos/
 2016_Segeln   2017_Segeln  '2020_02_Boa Vista'  2024-04_Versengold
```

If I start the album creator via Docker or Docker-Compose, it does not work either. I'm at a bit of a loss and hope that someone here has a brilliant idea.

Have a nice Sunday everyone!

**My Solution:**
The images must already be imported into Immich. So activate the automatic import via the external library in Immich and then the script will run perfectly.

**Comment by Salvoxia** [comment]
This is how the script works:
1. Request all images Immich knows of
2. Inspect each image and check if the path of the image starts with the `root_path`
3. If so, remove the `root_path` from the path and create the album name from the rest
4. Create all albums
5. Add images to albums

So in your current situation without any images in Immich, the log output you posted is to be expected.
It gets interesting once you've added the external library to Immich and the images have been imported.
One more thing is important: With Immich 1.106.0 there was a major refactoring of the API. Since then, the script only requests images from Immich that are not already part of an album. So if you manually add an image to an album, it will be ignored by the script.

**Comment by Warlik** [comment]
Oh, there was my big misunderstanding. I thought that the script creates the albums and then adds the images in the folders to the album. But it makes sense that nothing happened for me. 

Tonight the external path is read in and the script runs hourly with docker compose. I will report tomorrow whether everything worked. 

Thank you very much for your help!

**Comment by Warlik** [comment]
After the automatic import and the automatic call of the script went through last night, everything works perfectly. So it was just my misunderstanding of the function of the script. 

The result is exactly as I wanted it to be. Thank you very much for your work on the script and your help here!

**Comment by Peronia** [comment]
Hi @Salvoxia,
I stumbled across this too.
I tried the script with the path `/var/lib/docker/volumes/path_to_external/_data` and it shows no albums created (but there is one folder inside with pictures and Immich knows that).
So I found that issue and tried `/mnt/bilder` (this is the path from the Immich container, not from the host system where I launched the script, also used at the Immich GUI) and it worked.
Maybe it should be clearer formulated at the readme.

**Comment by Salvoxia** [comment]
Hi,
thanks for chiming in.
I already tried clarifying how to set the root path in the README's [root_path](https://github.com/Salvoxia/immich-folder-album-creator?tab=readme-ov-file#the-root_path) section.
If you have any suggestions on how to make it more clear, I'm open to them!

Best Regards,
Salvoxia

**Comment by Peronia** [comment]
As I see you already did it. So far I can't add anything.
