### ISSUE TITLE
Delete created albums

### ISSUE THREAD

**Issue by dushyantahuja** [Salvoxia/immich-folder-album-creator#27]
First of all - absolutely love this. 
However, and it's my fault, I ran the script without specifying the album separator. Now I would like to delete the created albums, and recreate using an album separator. Can you please help

**Comment by Salvoxia** [comment]
Hi,

glad you like the script!
I assume you've run the script from the Docker container? That highlights that there currently is no interactive mode to first verify the album names to be created when running from Docker, that's definitely something that should be added for manual runs in Docker.

Now to your actual question: Yes, it is conceivable to add a mode to the script to either delete ALL albums or only delete the album names constructed from the current assets and script arguments, if they exist.
The question is whether you are willing to wait until this is implemented ;)

Best Regards,
Salvoxia

**Comment by dushyantahuja** [comment]
Thanks - would be great if you can implement. For now, installed pgAdmin using instructions on this page https://immich.app/docs/guides/database-gui and ran 
`DELETE FROM public.albums

**Comment by Salvoxia** [comment]
Implemented with [v0.8.0](https://github.com/Salvoxia/immich-folder-album-creator/releases/tag/0.8.0).

**Comment by dushyantahuja** [comment]
Thank you
