### ISSUE TITLE
Integration in Unraid

### ISSUE THREAD

**Issue by Tschaeeens** [Salvoxia/immich-folder-album-creator#31]
Ist es möglich dein Skript auch in Unraid laufen zu lassen? Ich habe zwar einen Docker erstellt, aber dieser muss ja bestimmt auch mit dem immich docker kommunizieren können? Siehst du eine Möglichkeit? Danke dir.

**Comment by Salvoxia** [comment]
Ich hatte mit Unraid bisher noch nichts zu tun, daher kenne ich mich damit nicht aus.
Aber wenn Immich dort auch in einem Docker-Container läuft, sehe ich nicht, wieso es nicht möglich sein sollte. Es stimmt, dass das Skript insofern mit dem Immich Container kommunizieren können muss, als dass es auf die API zugreifen muss. Allerdings muss Immich selbst ja auch von außen erreichbar sein, um es benutzen zu können. Wenn man dem Skript also die Immich-Adresse als API URL gibt, die man auch selbst benutzen würde, um auf Immich zuzugreifen, sehe ich nicht, wieso das nicht funktionieren sollte.

Kannst Du vielleicht etwas konkreter werden, wo es Probleme gibt?

Gruß,
Salvoxia

**Comment by Tschaeeens** [comment]
Also ich habe den Docker erfolgreich laufen. Nur läuft der parallel zum immich docker als extra Docker. Den Root_Path habe ich auch gesetzt (auf den path wie in immich die externe Library eingebunden ist), aber ich glaube durch die 2 getrennten Docker kann das Script nicht arbeiten, da ich keinen Zugriff auf den Immich Container habe. Albums werden bis jetzt nicht erstellt.

**Comment by Salvoxia** [comment]
Einerseits müsste der Container jede Stunde Logs schreiben, die schonmal hilfreich wären.
Andererseits kannst Du zum Testen eine Shell im Container des Scripts öffnen und mal
`./immich_auto_album.sh`
aufrufen.
Das lässt das Script mit den von Dir gesetzten Environment Variablen laufen. Am Output sollte man dann auch erkennen, wo das Problem ist.

**Comment by Tschaeeens** [comment]
Super, den Befehl habe ich gesucht. Ich bekomme tatsächlich eine Fehlermeldung am Ende: 

`  File "/script/./immich_auto_album.py", line 416, in <module>
    input()
EOFError: EOF when reading a line`

Kannst du damit was anfangen?

**Comment by Salvoxia** [comment]
Ja, das klingt sehr danach, als ob der `ROOT_PATH` doch nicht zum Mount Path der External Library passt.
Kommunikation mit der API passt, er findet knapp 21k Bilder, aber erzeugt keine Albums daraus.
Unter welchem Pfad ist denn Deine external Library in den Immich Container gemounted und was hast Du für den `ROOT_PATH` im Script Container angegeben?

**Comment by Tschaeeens** [comment]
im immich container habe ich folgende: 

/mnt/user/Test/Bilder/:/mnt/user/Test

ROOT_PATH: /mnt/user/Test

**Comment by Salvoxia** [comment]
Ok, das sieht leider richtig aus ;) Wäre auch zu einfach gewesen.
Hast Du sonst noch weitere Variablen gesetzt, z.B. `ALBUM_LEVELS`?
Falls nicht, bitte mal `LOG_LEVEL` auf `DEBUG` setzen und nochmal laufen lassen. Der Output wird dann seeeehr umfänglich, sollte aber Licht ins Dunkel bringen. Wichtig sind einige zehn Zeilen ab dem Output
`Sorting assets to corresponding albums using folder name`

**Comment by Tschaeeens** [comment]
Erstmal danke für deine Hilfe. Ich finde immich mega, aber halt nur wenn die Albums gehen....
Nein ich habe erstmal keine Variablen gesetzt. Ich sende das komplette Log

`/script # ./immich_auto_album.sh
time=2024-08-07T21:38:08.005+02:00 level=DEBUG msg=root_path = ['/mnt/user/Test']
time=2024-08-07T21:38:08.005+02:00 level=DEBUG msg=root_url = XXX
time=2024-08-07T21:38:08.005+02:00 level=DEBUG msg=api_key = XXX
time=2024-08-07T21:38:08.005+02:00 level=DEBUG msg=number_of_images_per_request = 2000
time=2024-08-07T21:38:08.006+02:00 level=DEBUG msg=number_of_assets_to_fetch_per_request = 5000
time=2024-08-07T21:38:08.006+02:00 level=DEBUG msg=unattended = False
time=2024-08-07T21:38:08.006+02:00 level=DEBUG msg=album_levels = 1
time=2024-08-07T21:38:08.006+02:00 level=DEBUG msg=album_level_separator =  
time=2024-08-07T21:38:08.006+02:00 level=DEBUG msg=insecure = False
time=2024-08-07T21:38:08.006+02:00 level=DEBUG msg=ignore = 
time=2024-08-07T21:38:08.006+02:00 level=DEBUG msg=mode = CREATE
time=2024-08-07T21:38:08.006+02:00 level=DEBUG msg=delete_confirm = False
time=2024-08-07T21:38:08.008+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:08.014+02:00 level=DEBUG msg=http://192.168.0.110:8091 "GET /api/server-info/version HTTP/11" 200 33
time=2024-08-07T21:38:08.015+02:00 level=INFO msg=Detected Immich server version 1.111.0
time=2024-08-07T21:38:08.015+02:00 level=INFO msg=Requesting all assets
time=2024-08-07T21:38:08.016+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:08.393+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 844704
time=2024-08-07T21:38:08.429+02:00 level=DEBUG msg=Received 1000 assets with chunk 1
time=2024-08-07T21:38:08.431+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:08.761+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 897955
time=2024-08-07T21:38:08.798+02:00 level=DEBUG msg=Received 1000 assets with chunk 2
time=2024-08-07T21:38:08.799+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:09.079+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 858626
time=2024-08-07T21:38:09.109+02:00 level=DEBUG msg=Received 1000 assets with chunk 3
time=2024-08-07T21:38:09.111+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:10.142+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 845270
time=2024-08-07T21:38:10.172+02:00 level=DEBUG msg=Received 1000 assets with chunk 4
time=2024-08-07T21:38:10.174+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:10.873+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 838686
time=2024-08-07T21:38:10.905+02:00 level=DEBUG msg=Received 1000 assets with chunk 5
time=2024-08-07T21:38:10.906+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:11.620+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 854305
time=2024-08-07T21:38:11.655+02:00 level=DEBUG msg=Received 1000 assets with chunk 6
time=2024-08-07T21:38:11.656+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:12.094+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 861239
time=2024-08-07T21:38:12.118+02:00 level=DEBUG msg=Received 1000 assets with chunk 7
time=2024-08-07T21:38:12.119+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:12.485+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 866544
time=2024-08-07T21:38:12.517+02:00 level=DEBUG msg=Received 1000 assets with chunk 8
time=2024-08-07T21:38:12.522+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:12.894+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 867838
time=2024-08-07T21:38:12.926+02:00 level=DEBUG msg=Received 1000 assets with chunk 9
time=2024-08-07T21:38:12.927+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:13.316+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 850860
time=2024-08-07T21:38:13.351+02:00 level=DEBUG msg=Received 1000 assets with chunk 10
time=2024-08-07T21:38:13.352+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:13.725+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 858336
time=2024-08-07T21:38:13.757+02:00 level=DEBUG msg=Received 1000 assets with chunk 11
time=2024-08-07T21:38:13.758+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:14.122+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 843875
time=2024-08-07T21:38:14.152+02:00 level=DEBUG msg=Received 1000 assets with chunk 12
time=2024-08-07T21:38:14.153+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:14.539+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 850150
time=2024-08-07T21:38:14.564+02:00 level=DEBUG msg=Received 1000 assets with chunk 13
time=2024-08-07T21:38:14.566+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:14.980+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 839175
time=2024-08-07T21:38:15.018+02:00 level=DEBUG msg=Received 1000 assets with chunk 14
time=2024-08-07T21:38:15.019+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:15.420+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 834716
time=2024-08-07T21:38:15.457+02:00 level=DEBUG msg=Received 1000 assets with chunk 15
time=2024-08-07T21:38:15.459+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:15.877+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 828722
time=2024-08-07T21:38:15.907+02:00 level=DEBUG msg=Received 1000 assets with chunk 16
time=2024-08-07T21:38:15.909+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:16.306+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 832333
time=2024-08-07T21:38:16.342+02:00 level=DEBUG msg=Received 1000 assets with chunk 17
time=2024-08-07T21:38:16.343+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:16.741+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 829029
time=2024-08-07T21:38:16.769+02:00 level=DEBUG msg=Received 1000 assets with chunk 18
time=2024-08-07T21:38:16.771+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:17.195+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 841397
time=2024-08-07T21:38:17.222+02:00 level=DEBUG msg=Received 1000 assets with chunk 19
time=2024-08-07T21:38:17.223+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:17.635+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 846471
time=2024-08-07T21:38:17.662+02:00 level=DEBUG msg=Received 1000 assets with chunk 20
time=2024-08-07T21:38:17.663+02:00 level=DEBUG msg=Starting new HTTP connection (1): 192.168.0.110:8091
time=2024-08-07T21:38:18.028+02:00 level=DEBUG msg=http://192.168.0.110:8091 "POST /api/search/metadata HTTP/11" 200 797196
time=2024-08-07T21:38:18.062+02:00 level=DEBUG msg=Received 956 assets with chunk 21
time=2024-08-07T21:38:18.065+02:00 level=INFO msg=20956 photos found
time=2024-08-07T21:38:18.065+02:00 level=INFO msg=Sorting assets to corresponding albums using folder name
time=2024-08-07T21:38:18.081+02:00 level=INFO msg=0 albums identified
time=2024-08-07T21:38:18.082+02:00 level=INFO msg=Album list: []
Press enter to create these albums, Ctrl+C to abort
Traceback (most recent call last):
  File "/script/./immich_auto_album.py", line 416, in <module>
    input()
EOFError: EOF when reading a line
/script # `

**Comment by Salvoxia** [comment]
Hm, das ist deutlich weniger als erwartet. Dieser Output kommt eigentlich nur zustande, wenn das Script keine Assets findet, die zum root path passen oder nicht in weiteren Verzeichnissen unterhalb des root paths sind...
Kannst Du bitte mal noch den output von 
`ls -l /mnt/user/Test`
im Immich Container posten?

**Comment by Tschaeeens** [comment]
`drwxrwxrwx 1   99 users 4096 Feb  2  2019 '01_Bearbeitete Bilder'
drwxrwxrwx 1   99 users 4096 Apr 15 19:12  2003_Gardasee
drwxrwxrwx 1   99 users 4096 Feb  2  2019  2004_Gardasee
drwxrwxrwx 1   99 users 4096 Dec 27  2019 '2004_Urlaub Mallorca'
drwxrwxrwx 1   99 users 4096 Feb  2  2019 '2005_Konfirmation'
drwxrwxrwx 1   99 users 4096 Apr 20  2018  2006_Gardasee
drwxrwxrwx 1   99 users 4096 Apr 15 19:12 '2006_Robbie Williams Dresden`

**Comment by Salvoxia** [comment]
Hm, da stimme ich Dir zu, leider sehe ich immer noch nicht klar.
Bitte noch ein Test: Führe bitte den folgenden Befehl in einer beliebigen Shell aus (nicht in den Containern), in der `curl` verfügbar ist (`path.to.your.immich` und `xxxxxxxxxxxxxxxxxxxxx` jeweils durch Deine Immich URL bzw API Key ersetzen:
```bash
curl -L 'http://path.to.your.immich/api/search/metadata' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'x-api-key: xxxxxxxxxxxxxxxxxxxxx' -d '{
  "isNotInAlbum": true
}'
```

Das fragt die Immich API nach Assets ab, wie es das Script macht, und legt damit offen, wie die API die Bilder-Pfade zurückgibt. Irgendwo muss da was krumm sein.

**Comment by Tschaeeens** [comment]
Guten Morgen hier kommt folgendes: 

`{"albums":{"total":0,"count":0,"items":[],"facets":[]},"assets":{"total":250,"count":250,"items":[{"id":"93f19c11-d55c-446a-be43-94023b2200bb","deviceAssetId":"IMG_2467.JPG","ownerId":"cd1005d1-978c-4e95-aa12-cee5507494a2","deviceId":"Library Import","libraryId":"680d0012-e268-42fe-b31f-39285a97bcbf","type":"IMAGE","originalPath":"/mnt/user/Family/Bilder/Lotta/IMG_2467.JPG","originalFileName":"IMG_2467.JPG","originalMimeType":"image/jpeg","resized":true,"thumbhash":"6DgKFYZlgoipZ3eslweHh0mBkEQI","fileCreatedAt":"2023-09-02T09:54:06.000Z","fileModifiedAt":"2023-09-02T09:54:06.000Z","localDateTime":"2023-09-02T09:54:06.000Z","updatedAt":"2024-06-11T20:55:54.624Z","isFavorite":false,"isArchived":false,"isTrashed":false,"duration":"0:00:00.00000","livePhotoVideoId":null,"people":[],"checksum":"X9nqpmdzAauXiUoigFyS1bJPgGU=","stackCount":null,"isOffline":false,"hasMetadata":true,"duplicateId":null}`

ich wollte jetzt nicht alles kopieren.

**Comment by Salvoxia** [comment]
Guten Morgen, danke, ich denke, das reicht.
Der wichtige Teil ist der hier:
`"originalPath":"/mnt/user/Family/Bilder/Lotta/IMG_2467.JPG"`
Dieses Bild liegt also im Immich Container nicht unter `/mnt/user/Test/...` sondern unter `/mnt/user/Family`, fällt also nicht unter den root path.
Kannst Du bitte in einer Shell im Immich Container kontrollieren, dass es wirklich unter `/mnt/user/Test/..` noch weitere Unterverzeichnisse mit Bildern gibt und dass die auch in Immich auftauchen?

**Comment by Tschaeeens** [comment]
ich habe in immich insgesamt 3 externe mounts für jeweils drei Nutzer angelegt. Die API habe ich bei meinem root Nutzer erstellt. Komisch, dass dieser die Bibliothek, welche ich freigegeben habe anzeigt. ich habe diese Bibliothek beiden anderen Nutzern freigegeben. Ich lösche mal die Freigabe und schaue dann nochmal. Ich habe auch insgesamt über 200000 Bilder. Vielleicht ist dies auch ein Problem?

**Comment by Tschaeeens** [comment]
Jetzt habe ich die Bibliothek ausgemacht und nochmal den Befehl abgesetzt.

`{"albums":{"total":0,"count":0,"items":[],"facets":[]},"assets":{"total":1,"count":1,"items":[{"id":"d6d936e7-e508-4b65-be5b-f556776b03dd","deviceAssetId":"Jens4.jpg","ownerId":"1ddf2c77-6dc6-44d0-a83e-ed8f5100618c","deviceId":"Library Import","libraryId":"cf30c21d-342f-4d25-81ad-fc24b864b8ee","type":"IMAGE","originalPath":"/mnt/user/Test/2023_testzumlöschen/Test4.jpg","originalFileName":"Test4.jpg","originalMimeType":"image/jpeg","resized":true,"thumbhash":"GwgKFIKFaIeIh3dviHWVjQ/piA==","fileCreatedAt":"2005-05-16T19:14:58.000Z","fileModifiedAt":"2005-05-16T19:14:58.000Z","localDateTime":"2005-05-16T19:14:58.000Z","updatedAt":"2024-08-07T22:00:59.262Z","isFavorite":false,"isArchived":false,"isTrashed":false,"duration":"0:00:00.00000","livePhotoVideoId":null,"people":[],"checksum":"Uo/PaYQgT/W4TQrGECX6ILZCgbw=","stackCount":null,"isOffline":false,"hasMetadata":true,"duplicateId":"a77d3fc0-08c9-4d10-beb6-df123d39d6ee"}],"facets":[],"nextPage":null}}`

mit dem Befehl in der Console von unraid Albums kommt dieses Album auch. Er wirft dennoch den Fehler: 

`{"albums":{"total":0,"count":0,"items":[],"facets":[]},"assets":{"total":1,"count":1,"items":[{"id":"d6d936e7-e508-4b65-be5b-f556776b03dd","deviceAssetId":"Jens4.jpg","ownerId":"1ddf2c77-6dc6-44d0-a83e-ed8f5100618c","deviceId":"Library Import","libraryId":"cf30c21d-342f-4d25-81ad-fc24b864b8ee","type":"IMAGE","originalPath":"/mnt/user/Test/2023_testzumlöschen/Test4.jpg","originalFileName":"Test4.jpg","originalMimeType":"image/jpeg","resized":true,"thumbhash":"GwgKFIKFaIeIh3dviHWVjQ/piA==","fileCreatedAt":"2005-05-16T19:14:58.000Z","fileModifiedAt":"2005-05-16T19:14:58.000Z","localDateTime":"2005-05-16T19:14:58.000Z","updatedAt":"2024-08-07T22:00:59.262Z","isFavorite":false,"isArchived":false,"isTrashed":false,"duration":"0:00:00.00000","livePhotoVideoId":null,"people":[],"checksum":"Uo/PaYQgT/W4TQrGECX6ILZCgbw=","stackCount":null,"isOffline":false,"hasMetadata":true,"duplicateId":"a77d3fc0-08c9-4d10-beb6-df123d39d6ee"}],"facets":[],"nextPage":null}}`

**Comment by Salvoxia** [comment]
> Ich habe auch insgesamt über 200000 Bilder.

Das Script Log von gestern hat ca 20.9k Bilder gefunden. 

> ich habe in immich insgesamt 3 externe mounts für jeweils drei Nutzer angelegt. Die API habe ich bei meinem root Nutzer erstellt. 

Die API sieht immer nur die Bilder, die der Benutzer, zu dem der API Key gehört, auch sehen kann. Auch die Alben werden so auf Nutzerebene erzeugt. Wenn also jeder Benutzer Alben durch das Script erzeugt bekommen soll, brauchst Du im Prinzip für jeden Benutzer einen Container mit dem Script, mit für den Benutzer angepassten root path und API Key.

**Comment by Tschaeeens** [comment]
Okay. Aber bleibt dennoch immer der Fehler am Ende. Das heißt es werden leider keine Alben erzeugt. 3 Container sind kein Problem.

**Comment by Salvoxia** [comment]
Welcher Fehler?
> Er wirft dennoch den Fehler:
`{"albums":{"total":0,"count":0,"items":[],"facets":[]},"assets":{"total":1,"count":1,"items":[{"id":"d6d936e7-e508-4b65-be5b-f556776b03dd","deviceAssetId":"Jens4.jpg","ownerId":"1ddf2c77-6dc6-44d0-a83e-ed8f5100618c","deviceId":"Library Import","libraryId":"cf30c21d-342f-4d25-81ad-fc24b864b8ee","type":"IMAGE","originalPath":"/mnt/user/Test/2023_testzumlöschen/Test4.jpg","originalFileName":"Test4.jpg","originalMimeType":"image/jpeg","resized":true,"thumbhash":"GwgKFIKFaIeIh3dviHWVjQ/piA==","fileCreatedAt":"2005-05-16T19:14:58.000Z","fileModifiedAt":"2005-05-16T19:14:58.000Z","localDateTime":"2005-05-16T19:14:58.000Z","updatedAt":"2024-08-07T22:00:59.262Z","isFavorite":false,"isArchived":false,"isTrashed":false,"duration":"0:00:00.00000","livePhotoVideoId":null,"people":[],"checksum":"Uo/PaYQgT/W4TQrGECX6ILZCgbw=","stackCount":null,"isOffline":false,"hasMetadata":true,"duplicateId":"a77d3fc0-08c9-4d10-beb6-df123d39d6ee"}],"facets":[],"nextPage":null}}`

Das scheint einfach nochmal der selbe Output wie da oben? Copy/Paste Fehler?

**Comment by Salvoxia** [comment]
Letzte Aktivität war vor einer Woche, wenn sich in den nächsten 7 Tagen nichts tut, schließe ich hier.
Stale-Bot habe ich bislang keinen.

**Comment by Salvoxia** [comment]
Wird geschlossen. Bei weiteren Fragen oder Problemen gerne ein neues Issue öffnen.
