### ISSUE TITLE
Currently gettiung this error

### ISSUE THREAD

**Issue by JPurrier** [Salvoxia/immich-folder-album-creator#35]
File "/script/./immich_auto_album.py", line 416, in <module>
    input()
EOFError: EOF when reading a line

**Comment by Salvoxia** [comment]
Hi, 

Please see #32. This will look nicer in a future release.

Best Regards,
Salvoxia

**Comment by Salvoxia** [comment]
The mentioned nicer message is implemented in [0.9.0](https://github.com/Salvoxia/immich-folder-album-creator/releases/tag/0.9.0).
