### ISSUE TITLE
[Feature Request] Create directory based in album in Immich (Only External Library)

### ISSUE THREAD

**Issue by wes1993** [Salvoxia/immich-folder-album-creator#39]
Dear @Salvoxia,
Is possible to add an option that move the photos in folder based on Immich Album?

I know that using API we can see all the photos in the album (IMMICHHOST/api/albums/ALBUMID) so can you add an option that create the folder at FS level than move Photo in new path?

After library rescan we can use the normal behaviour to add the "new" photos to album.

This could be useful because i have created some album in Immich but at FS level I have all the photos togheter.

Best regards
Stefano

**Comment by Salvoxia** [comment]
Hi, 

thanks for your suggestions. To be frank, I think that is out of the scope of this script and does not fit very well with the current design.
At the moment you can run the script from anywhere where your Immich API can be reached. To perform actions on the file system, it must be run the Immich host.  
Moreover, a single file can be part of more than one album at the same time. How should the script behave if it finds the same file in multiple albums?  
Lastly, I think this is a pretty niche use case that could be solved by a one-time (admittedly potentially annoying and tedious) manual effort to straighten out the structure of the external library. Once that's done, you're good from that point on.

If in the future there is great interest for such a feature I might reconsider, but for now I won't implement it. I hope you understand.

Best Regards,
Salvoxia
