### ISSUE TITLE
Immich server version

### ISSUE THREAD

**Issue by makipsee** [Salvoxia/immich-folder-album-creator#49]
when i run the "dry run" i get this back i am on Immich version 1.114.0

```
docker run -e API_URL="http://192.168.1.2/api" -e API_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -e ROOT_PATH="/media/pi/PhoneBackups/myphone/S22/DCIM" salvoxia/immich-folder-album-creator:latest /script/immich_auto_album.sh 

time=2024-09-14T16:15:22.215+00:00 level=INFO msg=Detected Immich server version 1.105.1 or older
time=2024-09-14T16:15:22.216+00:00 level=CRITICAL msg=This script only works with Immich Server v1.106.0 and newer! Update Immich Server or use script version 0.8.1!
```

**Comment by Salvoxia** [comment]
Hi,

are you positive that `http://192.168.1.2/api` is the correct URL to the Immich API?
If you navigate to `http://192.168.1.2/api/server-info/version`, you should see something like this:
```json
{
    "major": 1,
    "minor": 114,
    "patch": 0
}
```

If you don't see that, the API_URL is not correct.

Best Regards,
Salvoxia

**Comment by makipsee** [comment]
again im sorry.. im just an idiot with this and trying to learn as i go... i was only entering the IPaddress without the port number... do you have a discord channel for answering the stupid questions that come up? lol  thank you again

**Comment by Salvoxia** [comment]
Don't be sorry, I'll happily answer all the questions you'll ever have! However (and this is where I am sorry), I or this project do not have a Discord channel. So please keep coming back here ;)

**Comment by makipsee** [comment]
Thank you so much! I just feel bad creating issues about things when it's just usually me not knowing what I'm doing lol
