### ISSUE TITLE
Naming the albums

### ISSUE THREAD

**Issue by GekoCH** [Salvoxia/immich-folder-album-creator#51]
Hy

What a great tool for creating albums, I really like it, thx a lot!!!

Just a small question if this is possible. Its not a big deal, but for me it would be great.
My folder structure looks like this:
```
/usr/src/app/external
├── 2024/
│   ├── Event 1/
│   │   └── Video/
│   ├── Event 2/
├── 2023/
│   ├── Event 3/
│   └── Event 4/
│   │   └── Video/
```

Since Immich can sort albums by year I would like to have my Albums named like:
```
Event 1
Event 2
Event 3
Event 4
```

Its probably already doable but I can't figure it out... currently it gets named like:
```
2024 Event 1
2024 Event 2
2023 Event 3
2023 Event 4
```

Thx for the help
Andy

**Comment by Salvoxia** [comment]
Hi,

take a look at [Album Level Ranges](https://github.com/Salvoxia/immich-folder-album-creator?tab=readme-ov-file#album-level-ranges). I think the example with `--album-levels="2,2"` is exactly what you're looking for.

Best Regards,
Salvoxia

**Comment by GekoCH** [comment]
wow thx a lot thats exactly what I was looking for
Thx a again for the great tool

Andy
