### ISSUE TITLE
Sent albums to archive

### ISSUE THREAD

**Issue by plaubi** [Salvoxia/immich-folder-album-creator#55]
Hey guys, 
there's one feature you guys maybe can add in a further release, but i don't really know if it's even possible:
im using external libraries which change a lot, like i have messanger photos synced from various phone. Those pictures are flooded with pictures i don't really want in my normal gallery. 
Since im using your script to generate albums after syncing those pictures, it would be nice to implement to sent those pictures to the archive as well. 
This way they would be automatically added to their defined album after syncing and added to the archive.

Is it even possible?

Thanks in advance!

**Comment by Salvoxia** [comment]
Hi,

I don't think I understood your workflow completely.
You're syncing images from smartphone messengers to an external library in Immich.
After that it gets blurry for me. What do you mean with "archive"? If you move images after Immich has picked them up, they will show as offline asset.
Could you maybe outline step by step what you are doing and why?

This script will not be able to make any file system changes, so moving images is not possible. But depending on what you ultimately want to achieve there might be ways the script could still help you.

Best Regards,
Salvoxia

**Comment by plaubi** [comment]
Sure thing:
im mounting pathes from my TrueNAS VM. 
Those pathes are mounted within my immich docker container and are getting periodically synced from a cloud with photos from a messenger app (twice a day).
With your script im adding those pictures of this path /mnt/pictures/<messerngername-pictures> to the album <messerngername-pictures>. 
But the issues: those pictures are sometimes flooded with spam, so in the end i don't want them in my timeline/main gallery of immich. I want them to be in the immich archive so they are not listed on the main. 
So in order to view them im going to albums, click the <messerngername-pictures> album and i can view them.

Hope you can understand my workflow a little bit better. In the end the script would only have to "move" (not physically move them) them internally to the immich archive.

**Comment by Salvoxia** [comment]
Thanks for the detailed explanation!
Every day you learn something new, today I learned about Immich's Archive feature. That was completely new to me, hence my confusion. I now looked it up in the API.  

If I get you right you would like an additional option to pass to the script, e.g. `--archive` (or `ARCHIVE=1` for Docker) to make the script "archive" any images it added to an album during the run.  
Is that summary correct and complete?

If so, that should be implemented easily.

Best Regards,
Salvoxia

**Comment by plaubi** [comment]
Yup that is correct, but im not quite sure about the complexity it needs, in my use case i only need those files (both pictures and videos) to be archived within specific albums/folders. 
Don't know if others need more options.

Summary, just to be sure: 
crontab before midnight: 
sync with the cloud is being triggered, new files being pulled to /mnt/photos/"messengername-pictures".

crontab midnight:
/mnt/photos/"messengername-pictures" is being rescanned by immich, new files being added to the gallery

Script features:
crontab 30 mins past midnight:
immich-folder-album-creator.py adds those new files to the album "messengername-pictures" AND adds them to the archive as well, but only those new files within this folder.

**Comment by Salvoxia** [comment]
Got it. Sounds simple enough :)
If you only want the archival to happen for a specific path only, you can add a second Docker container instance with that archive option enabled and [filtering](https://github.com/Salvoxia/immich-folder-album-creator?tab=readme-ov-file#filtering-for-assets) set to only include that/these path(s).

**Comment by plaubi** [comment]
Uff sounds like hell of a deal to add another docker, wouldn't that be possible within the immich docker with additional changes of your script?

**Comment by Salvoxia** [comment]
Hm, maybe there's a misunderstanding.
There are two ways of how to use the script, either as bare python script with a local Python isntallation, or with the Docker container. The Docker container is designed to fit nicely into the compose stack Immich comes with.

If you are using the script as a bare python script with manual crontab setup, then of course you don't need Docker but a separate entry in crontab to call the script with a different set of arguments.

What I'm trying to say is: If you pass the `--archive` argument, it will affect all images that are added during that run. So if you only want that to apply to a specific album, you must use the path filter to focus the script on that folders only. If you also want the script to create albums for other folders but without archiving, you need to configure a second entry in crontab to call the script without the `--archive` argument and without the path filter.

Would that be ok?

**Comment by plaubi** [comment]
Im not really into the docker stuff, so using a bare script is easier for me.
I understand what you are saying, but in my case the command would only point on the "messengername-pictures" folder with only the purpose of adding the pictures to album "messengername-pictures" and archiving all pictures within.

So my "main" command looks like this:
python3 /home/immich_auto_album.py --ignore Archiv:camera:messengername-pictures /mnt/photos https://url.com/api api-key 
(is there a way to get more values into --path-filter=folder1:folder2:folder3 haven't read anything about that, would be better to just use ignore in case there are more folders created)

Second command with the advanced feature:
python3 /home/immich_auto_album.py --archive /mnt/pictures/messengername-pictures https://url.com/api api-key

Maybe im trying the docker stuff oneday, but first of all i want it to work smoothly ;)

Thanks for your help so far!

**Comment by Salvoxia** [comment]
Alright, then we're talking about the same thing. I'll update this issue once the feature is ready for testing. I always the person to request a feature to be the first tester other than myself :)

**Comment by plaubi** [comment]
And regarding the question about path filters, is it possible to add more folders like: --path-filter=folder1:folder2:folder3 ?

Currently im using ignore everything except the folder i want, which is bad if new folders are created.

**Comment by Salvoxia** [comment]
Currently it's not possible to pass multiple path filters like with ignore, but while I'm at it...

**Comment by plaubi** [comment]
That'd be absolutly useful if you have a whole dir full of specific subfolders you want to add, but also some folders you want to exclude. If you ignore the ones you don't want, all new folders which are created in the future are automatically added to albums as well.

**Comment by Salvoxia** [comment]
Alright, here we go. It's ready for testing!

To automatically archive images after they were added to an album, run the script passing the new `--archive` option.
Also, you can now pass multiple path filters by simply passing `--path-filter` multiple times. Please note that the behavior of `--ignore` has been changed to no longer use a colon-separated string. Simply pass `--ignore` multiple times as well.

Take a short look at the updated README section for [Filtering](https://github.com/Salvoxia/immich-folder-album-creator?tab=readme-ov-file#filtering) as well as [Automatic Archiving](https://github.com/Salvoxia/immich-folder-album-creator?tab=readme-ov-file#automatic-archiving), which has some side effects to be aware of.

My tests looked good, if you confirm I'll build a new release.
Hoping to hear from you soon ;)

**Comment by plaubi** [comment]
Hey, that's insane how fast you react. Im trying to test it asap.

**Comment by Salvoxia** [comment]
Thanks for testing!

I still cannot say with good conscience to fully understand your setup, but if the script can now do everything you need, I'm glad.
All this will be included in the upcoming release, but since you're using the bare python script that's of no big consequence for you.

**Comment by Salvoxia** [comment]
Release with [v0.12.0](https://github.com/Salvoxia/immich-folder-album-creator/releases/tag/0.12.0).
