### ISSUE TITLE
[FR] Specify multiple root paths

### ISSUE THREAD

**Issue by fl4shback** [Salvoxia/immich-folder-album-creator#6]
Hi!

Do you think it would be possible to support inputting multiple root paths ?
I'm currently running multiple containers on a swarm cron planning for this.

Thanks.

**Comment by Salvoxia** [comment]
Absolutely. 
However, we need to consider what happens if the same folder name is found in different root paths. The most straight-forward behavior would be to simply put all images from all root paths in the same album. Is that what you would expect as well?

**Comment by fl4shback** [comment]
For my case, I don't have duplicate folder names in the different root folders but I guess It would be expected to reuse the same album, yes.

**Comment by Salvoxia** [comment]
Implementation is done.
Depending on how you use the script you can:
 - add additional root paths using `-r` or `--root-path` when calling the python script like so:
   ```bash
   python ./immich_folder_album_creator.py -r /another/root/path /my/default/root/path http://immich_server:3001/api myApiKey
   ```
  - List all root paths as a comma separated list in the environment variable `ROOT_PATH` of the Docker container (make sure to pull the `latest` image) like so:
   `-e ROOT_PATH=/my/default/root/path,/another/root/path`

Worked as expected in my tests.
If you can confirm this for you as well, I'll finish by updating the documentation and tag a new release with this.

**Comment by fl4shback** [comment]
Looks good on my side !
Just did a test and it worked as expected too.
Thanks !
