### ISSUE TITLE
ERROR "No connection adapters were found"

### ISSUE THREAD

**Issue by NWPU-ZYKerman** [Salvoxia/immich-folder-album-creator#69]
Hi, 
I use the command

`docker run --name immich-folder-album-creator -e TZ="Europe/Berlin" -e CRON_EXPRESSION="0 * * * *" -e API_URL="localhost:30041/api" -e API_KEY="*************************" -e ROOT_PATH="/mnt/photography,/mnt/archieve" --network host salvoxia/immich-folder-album-creator:latest`

and it didn't work for my Immich. I went to the shell inside the docker and tried 

`/bin/sh immich_auto_album.sh`

and got the output
![image](https://github.com/user-attachments/assets/bb43af19-1f1e-488e-89bc-d14e6bc8e8e4)

How to fix that?

**Comment by Salvoxia** [comment]
Hi,

you need to specify the URL scheme with your `API_URL`, e.g. `API_URL="http://localhost:30041/api"` or `API_URL="https://localhost:30041/api"`.

Best Regards,
Salvoxia

**Comment by NWPU-ZYKerman** [comment]
It works! Thank you.
-----------------------------------------------------------------------------------------------
Now I'm encountering another problem. I see from the output that it will generate 6 albums:
![image](https://github.com/user-attachments/assets/92437f74-f7c9-4d7f-95c8-d3000dd97313)
My files' strcture is

```
mnt
 |-Photography
 |   |-TEMP
 |   | -<several empty folders which I will upload my photos to in the future>
 |-Archive
     |-2023
     |-2022
     |- ......
```

Are there any chances that I can set up only 2 albums for folder photography and archive separately?

**Comment by Salvoxia** [comment]
Hi,

Try setting your `ROOT_PATH` to `/mnt` only.

Best Regards,
Salvoxia

**Comment by NWPU-ZYKerman** [comment]
![Screenshot_20241013_193844.jpg](https://github.com/user-attachments/assets/d737ba86-8b65-4e04-8228-e1ce15be0c2a)

The list is empty now :(

**Comment by Salvoxia** [comment]
Did you create the 6 albums from before?
The script will by default only create albums for assets that are not already assigned to an album. If you already create the albums before, you have two options:
1. Delete them by running the script with the same arguments, but also passing `-e MODE="CLEANUP"` as well as `-e DELETE_CONFIRM="true"` to let the script delete the albums it created before, then run it again with the corrected `ROOT_PATH`
2. Pass `-e FIND_ALBUMS_IN_FOLDERS="true"` to create the new albums even though the images are already part of the other albums.

If you did NOT create the albums from before, please post the full call you used for running the container the second time and also run the script with `-e LOG_LEVEL="DEBUG"`  to make it log more and possibly give a hint why it ignored the assets it found.

**Comment by NWPU-ZYKerman** [comment]
Yay it's now works perfectly. Many thanks for helping me with this stuff.
