### ISSUE TITLE
Multiple import paths in external library

### ISSUE THREAD

**Issue by DJF3** [Salvoxia/immich-folder-album-creator#8]
My photos are on a NAS (readonly NFS share) mounted in Immich. 
The external album has 2 _import paths_: 

```
/usr/src/app/mypics/2023/
                        2023-jan
                        2023-feb
                        2023-mar
/usr/src/app/mypics/_mobile/2023/   
                                2023-photos-anna
                                2023-photos-dj
```
**FIRST** Go to `/mypics/2023` and run the script for the current folder . As expected the script generates albums
- "2023-jan", "2023-feb" and "2023-mar" 

**SECOND** Go to `/mypics/_mobile/2023/` and run the script again for the current folder:
At this point I would expect the script to generate albums 
- "2023-photos-anna" and "2023-photos-dj"

But these are not created. 

Is this code compatible with "multiple import paths" in an external library?

**Comment by Salvoxia** [comment]
Yes it is, see [here](https://github.com/Salvoxia/immich-folder-album-creator/releases/tag/0.3.0).
Can you please list all arguments you passed to the script / set as environment variables (if you are using the Docker container) and/or provide the initial log output of the script when run with `--log-level DEBUG` / `--env-var LOG_LEVEL=DEBUG`?

**Comment by DJF3** [comment]
Ah, that's interesting. I was using version 0.20, not later releases which support additional root_paths!
Let me re-test.

**Comment by DJF3** [comment]
Working fine with the new code, _thank you!_
