### ISSUE TITLE
discard the 2nd last folder if it startswith last folder during create_album_name

### ISSUE THREAD

**Issue by rock-meister** [Salvoxia/immich-folder-album-creator#82]
Many of the photomanagement software create folder like "2024-12-13" and put all the image files in it during import.  Most of us put it under a parent folder "2024".  Thus folder structure looks like "2024/2024-12-13".  Hence, the created album looks like "2024 2024-12-13".  The proposed solution is to discard the 2nd last folder if it startswith last folder during create_album_name.

I did a quick hack and it works.  The working code snippet is provided below.

```
    logging.debug("album_name_chunks before stripping the 2nd last folder = %s", album_name_chunks)
    if len(album_name_chunks) > 1:
        # if the 2nd last folder startswith the last folder, remove the 2nd last folder
        # for example: "2024/2024-12-13" -> "2024-12-13"
        if album_name_chunks[-1].startswith(album_name_chunks[-2]):
            album_name_chunks.pop(-2)
    logging.debug("album_name_chunks = %s", album_name_chunks)
```

**Comment by Salvoxia** [comment]
Can you elaborate on the complete folder structure and the desired album names? If you only want album names to be called like `2024-12-13`, you could simply go with `--album-levels="-1,-1"`. So is there another folder level above `2024` that should be included in the album's name?

**Comment by rock-meister** [comment]
You are correct.  I should used --album-levels="-1,-1" to pick up all the leaf folders.  It would have solved my problem.

**Comment by Salvoxia** [comment]
Closing this as solved.
