### ISSUE TITLE
Force Run in docker compose

### ISSUE THREAD

**Issue by yodaphone** [Salvoxia/immich-folder-album-creator#85]
Is there a way to force the script to run in docker compose mode?

**Comment by Salvoxia** [comment]
Can you elaborate on what exactly you mean with docker compose mode?

**Comment by archont00** [comment]
The container created via docker compose waits for cron to trigger the re-scanning of the assets. Is it possible to force immediate re-scanning in a running container? (Instead of using `docker run --rm ...` with a temporary container.)

**Comment by Salvoxia** [comment]
Ah, now I understand.
Yes, absolutely.
For a dry-run, run
`docker exec <container_name> /bin/sh -c "/script/immich_auto_album.sh"`
Replace `<container_name` with the name of your docker-compose container.

For the real thing, run
`docker exec <container_name> /bin/sh -c "UNATTENDED=1 /script/immich_auto_album.sh"`

**Comment by archont00** [comment]
I have created a PR for this info and to correct the API key volume mount (it was in a wrong worker).

https://github.com/Salvoxia/immich-folder-album-creator/pull/92

**Comment by Salvoxia** [comment]
Merged
