### ISSUE TITLE
Need help with path to ext lib

### ISSUE THREAD

**Issue by Lazy131** [Salvoxia/immich-folder-album-creator#91]
Thanks Salvoxia for this amazing work. Really appreciate it as this is exactly what I needed. Because I feel like during your lifetime software changes all the time but if you maintain a good folder structure this will stay and can be reused.

However I am struggling passing the external lib path to the script. In the output it tells me that it foud 17k photos but it would not find an album.
time=2024-12-24T14:45:48.667+01:00 level=INFO msg=Detected Immich server version 1.123.0
time=2024-12-24T14:45:48.667+01:00 level=INFO msg=Requesting all assets
time=2024-12-24T14:45:54.661+01:00 level=INFO msg=25707 photos found
time=2024-12-24T14:45:54.661+01:00 level=INFO msg=Sorting assets to corresponding albums using folder name
time=2024-12-24T14:45:54.681+01:00 level=INFO msg=0 albums identified
time=2024-12-24T14:45:54.681+01:00 level=INFO msg=Album list: []
Press enter to create these albums, Ctrl+C to abort

![image](https://github.com/user-attachments/assets/0e4f6192-a21d-4c8c-b2ef-687c30469152)

![image](https://github.com/user-attachments/assets/638fad0e-6acc-442a-94a7-7c1b51c4bfb1)

![image](https://github.com/user-attachments/assets/18e8b5ec-8cd7-4234-80c0-e29de4b8b368)

Can you help me what exactly I need to pass as path to external lib? Tried a lot of combinations already

Thanks!

**Comment by Salvoxia** [comment]
Hi,

the `root_path` to pass to the script is the path you added to your external library in Immich, so that's `/Bilder/Handy`.

Merry Christmas!

**Comment by Lazy131** [comment]
It works, thank you very much.

Also merry christmas to you and your loved once :)
